name: Foundry

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        decimals: [0, 6, 8, 18, 24]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run forge fmt
        run: forge fmt --check

      - name: Run forge tests
        run: DECIMALS=${{matrix.decimals}} forge test -vvv
